CREATE VIEW `CURRENT_TYPE_PRICES` AS 
select 
	`MODEL_TYPE_PRICE`.`MODEL_TYPE_ID` AS `MODEL_TYPE_ID`,
	`MODEL_TYPE_PRICE`.`PRICE` AS `PRICE` 
from 
	`MODEL_TYPE_PRICE` 
where (
	(`MODEL_TYPE_PRICE`.`SOURCE` = 'AMAZON') 
	and (`MODEL_TYPE_PRICE`.`TIMESTAMP` = (select max(`MODEL_TYPE_PRICE`.`TIMESTAMP`) from `MODEL_TYPE_PRICE`)))