--SMARTPHONE
INSERT INTO `SMARTPHONE`
(`NAME`,`BRAND`,`RELEASED`,`IMAGE_LINK`,`DESIGN`,`DISPLAY`,`LENGTH`,`WIDTH`,`CPU`,`UPDATES`,`CAMERA`,`BATTERY`,`BATTERYSIZE`,`SD_SLOT`,`SIM_CARDS`,`NOTCH`,`WATERPROOF`,`HEADPHONE_JACK`)
VALUES 
('<{NAME: }>','<{BRAND: }>','<{RELEASED: }>','<{IMAGE_LINK: }>','<{DESIGN: }>','<{DISPLAY: }>','<{LENGTH: }>','<{WIDTH: }>','<{CPU: }>','<{UPDATES: }>','<{CAMERA: }>','<{BATTERY: }>','<{BATTERYSIZE: }>','<{SD_SLOT: }>','<{SIM_CARDS: }>','<{NOTCH: }>','<{WATERPROOF: }>','<{HEADPHONE_JACK: }>');
--Each PHONE_MODEL of the above SMARTPHONE and directly after the corresponding MODEL_TYPE's
INSERT INTO `PHONE_MODEL`
(`SMARTPHONE_ID`,`STORAGE`,`MEMORY`)
SELECT 
	MAX(ID),'<{STORAGE: }>','<{MEMORY: }>'
FROM
	SMARTPHONE;
--One or more MODEL_TYPE's to the above PHONE_MODEL
INSERT INTO `MODEL_TYPE`
(`PHONE_MODEL_ID`,`VENDOR_ID`,`NAME`,`ITEM_ID`,`LINK`,`LAST_UPDATED`)
SELECT
	MAX(ID),'AMAZON_DE','<{NAME: }>','<{ITEM_ID: }>','','0000-00-00 00:00:00'
FROM
	PHONE_MODEL;