CREATE TABLE `MODEL_TYPE_PRICE` (
  `MODEL_TYPE_ID` int(11) NOT NULL,
  `PRICE` double(10,2) NOT NULL DEFAULT '0.00',
  `TIMESTAMP` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  KEY `MODEL_TYPE_ID` (`MODEL_TYPE_ID`),
  FOREIGN KEY (`MODEL_TYPE_ID`) REFERENCES `MODEL_TYPE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;