CREATE TABLE `PHONE_MODEL` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `SMARTPHONE_ID` int(11) NOT NULL,
  `STORAGE` int(11) NOT NULL,
  `MEMORY` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `SMARTPHONE_ID` (`SMARTPHONE_ID`),
  FOREIGN KEY (`SMARTPHONE_ID`) REFERENCES `SMARTPHONE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;